services:
  - type: web
    name: underwater-treasure-hunt
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin-allow-popups